spring:
  application:
    name: lms
  server:
    port: ${SERVER_PORT:8080}
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true
secret:
  key: ${SECRET_KEY}

logging:
  level:
    root: WARN                               # Default log level for everything
    com.codingwork.lms: DEBUG                # Enable detailed logging for your app package
    org.springframework.web: INFO            # Moderate detail for Spring Web
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG           # Fine-grained logging for MongoTemplate
