spring:
  application:
    name: lms
  server:
    port: ${SERVER_PORT:8080}
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true
secret:
  key: ${SECRET_KEY}

logging:
  level:
    root: WARN
    com.codingwork.lms: DEBUG
    org.springframework.web: INFO