spring:
  application:
    name: lms
  server:
    port: ${SERVER_PORT:8080}
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: lmsdb
      auto-index-creation: true
  config:
    import: optional:file:.env[.properties]

secret:
  key: ${SECRET_KEY}